### ISSUE TITLE
Inclusion in YunoHost?

### ISSUE THREAD

**Issue by mxmilkiib** [maxerenberg/cabbagemeet#1]
Currently the YunoHost turnkey private cloud distro only has the option of Framadate for arranging meetings. Inclusion of CabbageMeet in the sites it can deploy would be very handy!

https://yunohost.org

https://yunohost.org/en/packaging_publishing
https://yunohost.org/en/packaging_sso_ldap_integration

**Comment by maxerenberg** [comment]
Looks very interesting! Unfortunately I don't have the time right now to publish and maintain this app on other platforms. But if I get some more time in the future, I'll definitely take another look. :smile:
